### ISSUE TITLE
순례 왔습니다.

### ISSUE THREAD

**Issue by ghost** [trustfarm-dev/TFAcademy#11]
![Alt Text](https://camo.githubusercontent.com/f550284bb57a285832dc8d5b2bbb3d8fa6fc1b1f/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76464b716e43644c504e4f4b632f67697068792e676966)

**Comment by lnhog403** [comment]
![Alt Text](https://camo.githubusercontent.com/f550284bb57a285832dc8d5b2bbb3d8fa6fc1b1f/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76464b716e43644c504e4f4b632f67697068792e676966)

**Comment by trustfarm-dev** [comment]
반갑습니다. gogogo~~~
