### ISSUE TITLE
쉬는시간이 오면 짖는 개

### ISSUE THREAD

**Issue by rainwaltz** [trustfarm-dev/TFAcademy#18]
멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍

**Comment by yiedw** [comment]
왈왈왈왈왈왈

**Comment by rainwaltz** [comment]
좀 더 우렁차게 월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월

**Comment by trustfarm-dev** [comment]
멍멍.~~~

**Comment by rockjeon** [comment]
오빠 너무 멋있쪄

**Comment by ghost** [comment]
![Alt Text](https://media.giphy.com/media/4Zo41lhzKt6iZ8xff9/giphy.gif)
